<?php

/**
 * Add labelwithgroup form
 *
 * @package    mod_labelwithgroup
 * @copyright  2021 4Linux  {@link https://4linux.com.br/}
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die;

require_once ($CFG->dirroot.'/course/moodleform_mod.php');
require_once ($CFG->dirroot . '/mod/labelwithgroup/classes/templatefactory.php');

use \mod_labelwithgroup\classes\templatefactory;

class mod_labelwithgroup_mod_form extends moodleform_mod {

    function definition() {
        global $PAGE, $CFG;

        $PAGE->force_settings_menu();

        $mform = $this->_form;

        // general header
        $mform->addElement('header', 'generalhdr', get_string('general'));

        // Templates field
        $templatesinfo = [
            'none' => get_string('templatenone', 'mod_labelwithgroup'),
            'collapse' => get_string('templatecollapse', 'mod_labelwithgroup'),
            'slide' => get_string('templateslide', 'mod_labelwithgroup'),
            'collapse-slide' => get_string('templatecollapseslide', 'mod_labelwithgroup'),
        ];

        $mform->addElement('select', 'templatetype', get_string('template', 'mod_labelwithgroup'), $templatesinfo);

        // Title field
        $mform->addElement('text', 'title', get_string('title', 'mod_labelwithgroup'), 'maxlength="255" size="100" ');
        $mform->setType('title', PARAM_TEXT);
        $mform->hideIf('title', 'templetype', 'in', [templatefactory::$TEMPLATE_TYPE_SLIDE, templatefactory::$TEMPLATE_TYPE_NONE]);

        // Editor
        for ($i = 1; $i <= 25; $i++) {
            $mform->addElement('editor', 'content' . $i, get_string('content', 'mod_labelwithgroup'));
            $mform->setType('content', PARAM_RAW);

            if ($i !== 1) {
                $mform->hideIf('content' . $i, 'templatetype', 'in', [templatefactory::$TEMPLATE_TYPE_COLLAPSE, templatefactory::$TEMPLATE_TYPE_NONE]);
            }
        }

        // Button
        $mform->addElement('button', 'addslide', get_string("buttonaddslide", 'mod_labelwithgroup'));
        $mform->hideIf('addslide', 'templatetype', 'in', [templatefactory::$TEMPLATE_TYPE_COLLAPSE, templatefactory::$TEMPLATE_TYPE_NONE]);

        // Group field
        $groups = groups_get_all_groups($this->get_course()->id);

        $groupsinfo = [];

        $groupsinfo[-1] = get_string('allparticipants');

        foreach($groups as $group) {
            $groupsinfo[$group->id] = $group->name;
        }

        $mform->addElement('select', 'groupid', get_string('group'), $groupsinfo);

        //  does not add "Show description" checkbox meaning that 'intro' is always shown on the course page.
        $mform->addElement('hidden', 'showdescription', 1);
        $mform->setType('showdescription', PARAM_INT);

        // Standard fields
        $this->standard_intro_elements(get_string('labelwithgrouptext', 'labelwithgroup'));


        $PAGE->requires->js_call_amd('mod_labelwithgroup/form_handler', 'init', [$CFG->lang]);

        $this->standard_coursemodule_elements();

        $this->add_action_buttons(true, false, null);
    }

    function data_preprocessing(&$default_values)
    {
        global $DB;

        parent::data_preprocessing($default_values); // TODO: Change the autogenerated stub

        $id = $default_values['instance'];

        if (!empty($id)) {
            $contents = $DB->get_records('labelwithgroup_content', ['labelwithgroup_id' => $id]);

            $contentsid = array_keys($contents);

            for ($i = 1; $i <= count($contents); $i++) {
                $attrname = 'content' . $i;
                $default_values[$attrname] = [ 'text' => $contents[$contentsid[$i - 1]]->content];
            }
        }


    }

    function data_postprocessing($data)
    {
        parent::data_postprocessing($data);

        $templateentity = templatefactory::get_template_by_type($data->templatetype);

        $content = [];
        for ($i = 1; $i <= 25; $i++) {
            $attrname = 'content' . $i;

            if (!empty($data->$attrname['text']) ) {
                $content[] = $data->$attrname['text'];
            }
        }

        $data->content = $content;

        $data->introeditor['text'] = $templateentity->process_content($content, $data->title, $data->groupid, $data->course);
    }

}
